### ISSUE TITLE
Yahoo: expected to find css ".First.Last" 1 time but there were no matches

### ISSUE THREAD

**Issue by TNT-c** [philipfong/free-agent-sleeper#14]
### Unable to add player: 

RSpec::Repeat: 1st try error in ./spec/yahoo/add_free_agent.rb:49:
  expected to find css ".First.Last" 1 time but there were no matches
RSpec::Repeat: 2nd try error in ./spec/yahoo/add_free_agent.rb:49:
  expected to find css ".First.Last" 1 time but there were no matches
RSpec::Repeat: 3rd try error in ./spec/yahoo/add_free_agent.rb:49:
  expected to find css ".First.Last" 1 time but there were no matches
F

Failures:

  1) Add free agents to Fantasy Football league Log in and add/drop player
     Failure/Error: page.should have_css('.First.Last', :count => 1)
       expected to find css ".First.Last" 1 time but there were no matches
     # ./spec/yahoo/add_free_agent.rb:21:in `add_drop'
     # ./spec/yahoo/add_free_agent.rb:50:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:26:in `block (2 levels) in <top (required)>'

Finished in 3 minutes 4 seconds (files took 13.67 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/yahoo/add_free_agent.rb:49 # Add free agents to Fantasy Football league Log in and add/drop player

**Comment by superflysocal** [comment]
I am having the same issue.  is this currently still working?

**Comment by superflysocal** [comment]
> ### Unable to add player:
> RSpec::Repeat: 1st try error in ./spec/yahoo/add_free_agent.rb:49:
> expected to find css ".First.Last" 1 time but there were no matches
> RSpec::Repeat: 2nd try error in ./spec/yahoo/add_free_agent.rb:49:
> expected to find css ".First.Last" 1 time but there were no matches
> RSpec::Repeat: 3rd try error in ./spec/yahoo/add_free_agent.rb:49:
> expected to find css ".First.Last" 1 time but there were no matches
> F
> 
> Failures:
> 
> 1. Add free agents to Fantasy Football league Log in and add/drop player
>    Failure/Error: page.should have_css('.First.Last', :count => 1)
>    expected to find css ".First.Last" 1 time but there were no matches
>    # ./spec/yahoo/add_free_agent.rb:21:in `add_drop'
>    # ./spec/yahoo/add_free_agent.rb:50:in `block (2 levels) in <top (required)>'
>    # ./spec/spec_helper.rb:26:in `block (2 levels) in <top (required)>'
> 
> Finished in 3 minutes 4 seconds (files took 13.67 seconds to load)
> 1 example, 1 failure
> 
> Failed examples:
> 
> rspec ./spec/yahoo/add_free_agent.rb:49 # Add free agents to Fantasy Football league Log in and add/drop player

I am having the same issue.  Is this script still working?

**Comment by superflysocal** [comment]
Still can't get this to work.
From running it realtime, it seems that the click_button('Search') command is not working.  It doesn't pull up the page with the selected player is on.

**Comment by ghost** [comment]
Same issue with me.  Would love it if the Dev, or someone, could resolve this!

**Comment by dannychran** [comment]
@philipfong any chance you regained some passion for this project?

**Comment by ghost** [comment]
I'm keeping my fingers crossed that this project isn't dead.  I've tried finding Philip elsewhere to ask him about this project but without any luck.

**Comment by kuroshhashemi** [comment]
Hi I created the following PR: https://github.com/philipfong/free-agent-sleeper/pull/18. It's working for me.  Please review and merge.  However fair warning, I'm not really a programmer (esp not a Ruby one), so I'm not sure if my approach is right
